
name: Build and deploy ASP.Net Core app to an Azure Web App

env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8'                 # set this to the .NET Core version to use
  Solution : ../../Asp.netCoreWebApp.sln
  package: ../../publish

on:
  workflow_dispatch:



permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore ${{env.Solution}}
     
      - name: Build with dotnet
        run: dotnet build ${{env.Solution}} --configuration Release --no restore

      - name: Publish
        run: dotnet publish ${{env.Solution}} --configuration Release --no build --output ${{env.package}}

      - name: Deploy
        uses: actions/webapps-deploy@v2
        with:
          app-name: 'AspnetCoreWebApp20250623202505'
          publish-profile: ''
          package: ${{env.package}}
           

      
